project:
  type: website
  output-dir: docs

website:
  title: "Liangchenn's Blog"
  favicon: "asset/favicon.png"
  navbar:
    logo: "asset/favicon.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/liangchenn/
      - icon: twitter
        href: https://twitter.com/@liangchennchen/
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css



